"""Coordinador de operaciones de base de datos del iPod (Fase 2, Etapa 2c)."""
from __future__ import annotations

from .apply import (
    ApplyError,
    ApplyResult,
    PostCommitVerifyError,
    StalePlanError,
    apply,
    clear_inflight_marker,
    default_commit_dir,
    get_inflight_marker,
    get_inflight_path,
    purge_staging_temps,
    recover_inflight_commit,
    set_inflight_marker,
)
from .consent import (
    ConsentRecord,
    ConsentRequiredError,
    default_consent_dir,
    get_consent_path,
    get_consent_record,
    has_music_app_consent,
    mark_first_write_committed,
    record_music_app_consent,
    revoke_music_app_consent,
)
from .plan import (
    DATABASE_TARGET_RELPATHS,
    InconsistentArtifactsError,
    Plan,
    PlanError,
    PreStateFingerprint,
    UnsafeDeviceError,
    create_plan,
)

__all__ = [
    "ConsentRecord",
    "ConsentRequiredError",
    "default_consent_dir",
    "get_consent_path",
    "get_consent_record",
    "has_music_app_consent",
    "record_music_app_consent",
    "mark_first_write_committed",
    "revoke_music_app_consent",
    "DATABASE_TARGET_RELPATHS",
    "PreStateFingerprint",
    "Plan",
    "PlanError",
    "UnsafeDeviceError",
    "InconsistentArtifactsError",
    "create_plan",
    "ApplyResult",
    "ApplyError",
    "StalePlanError",
    "PostCommitVerifyError",
    "apply",
    "default_commit_dir",
    "get_inflight_path",
    "set_inflight_marker",
    "clear_inflight_marker",
    "get_inflight_marker",
    "recover_inflight_commit",
    "purge_staging_temps",
]
